GET https://localhost:7054/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3RyaW5nIiwiZmlyc3ROYW1lIjoic3RyaW5nIiwibGFzdE5hbWUiOiJzdHJpbmciLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzdHJpbmdAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwibmJmIjoxNzg4MDIyNzA4LCJleHAiOjE3ODgwMjQ1MDgsImlzcyI6IkFwcGxpY2F0aW9uQXBpIiwiYXVkIjoiQXBwbGljYXRpb25DbGllbnQifQ.i-yXIzZj0rKjzw31JetGtqhXbPz1o4KERwK5wh3eJlY

###
GET https://localhost:7054/api/auth/all
Authroization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJmaXJzdE5hbWUiOiJGaXJzdCBuYW1lIG9mIHRoZSBhZG1pbiIsImxhc3ROYW1lIjoiSGlzIG9yIGhlciBsYXN0IG5hbWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBhZG1pbi5jZW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW4iLCJVc2VyIl0sIm5iZiI6MTc4ODAyMzA0NSwiZXhwIjoxNzg4MDI0ODQ1LCJpc3MiOiJBcHBsaWNhdGlvbkFwaSIsImF1ZCI6IkFwcGxpY2F0aW9uQ2xpZW50In0.J09Gab_z5w24jvf5cQSzgfPgTeIDsrFVtW3ONSpBuRw

###